### ISSUE TITLE
Q: what should translation data look like

### ISSUE THREAD

**Issue by gereons** [zaroth/netrunner-cards-json#197]
I'm opening this issue to get a consensus on what translation data for untranslated cards should look like. Right now, we have a mixture of styles:

- a `code` property with `null` title and nothing else, eg. in de/23s.de.json
- no mention of the card at all, also in de/23s.de.json
- english text in a non-english translation file, eg. de/td.de.json

I'd suggest converting every untranslated card to option 2, and removing all resulting empty files, and I volunteer to make the necessary changes. Other opinions?

**Comment by ANR-PeterPan** [comment]
I think I can translate Flashpoint-Cycle for german shortly, but generally i would choose option 3 as a user.
Better see english text than nothing.

**Comment by ANR-PeterPan** [comment]
and imho it is easier to replace english text with foreign language having the skeleton of code already implemented

**Comment by gereons** [comment]
This is only about how we want to store and edit the data, it's not about what users see.
Having the english text repeated in 8 translation files would really suck. And like I said, we don't have that consistently ATM.

**Comment by ANR-PeterPan** [comment]
Ok, for me its easier when I have the english Text because I have the skeleton of code and I can use the special marks like [credit] <trace> <strong> etc without typing them for my own every time.

**Comment by Alsciende** [comment]
I think it's better to have option 3 in the translation files. It makes it easier for translators to translate the data (as was pointed by @ANR-PeterPan ). In the database, the non-translated text is not stored. It's only in the translation files.

The script "update_locales.coffee" works according to option 3, so the only inconsistencies come from manual creation of the files. That can be easily fixed by using the script. In any case, there are no consequences to the inconsistencies with respect to the database.
